# Generated by Django 3.0.7 on 2020-08-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_choir_decoration_media_pastors_protocol_sanitation_security_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Ushers',
        ),
    ]
