# Generated by Django 3.0.7 on 2020-08-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='fbook',
        ),
        migrations.RemoveField(
            model_name='events',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='events',
            name='twitter',
        ),
    ]
